
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admlkjust
 */
public class SkaiciuoklesForma extends javax.swing.JFrame {

    /**
     * Creates new form SkaiciuoklesForma
     */
    public SkaiciuoklesForma() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstNumberText = new javax.swing.JTextField();
        secondNumberText = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        plusButton = new javax.swing.JButton();
        minusButton = new javax.swing.JButton();
        AnswerLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Skaičiuotuvas");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(null);
        getContentPane().add(FirstNumberText);
        FirstNumberText.setBounds(109, 87, 125, 20);

        secondNumberText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secondNumberTextActionPerformed(evt);
            }
        });
        getContentPane().add(secondNumberText);
        secondNumberText.setBounds(109, 135, 125, 20);

        jLabel1.setText("Pirmas skaičius");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(109, 67, 98, 14);

        jLabel2.setText("Antras skaičius");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(109, 118, 97, 14);

        plusButton.setText("+");
        plusButton.setToolTipText("add");
        plusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(plusButton);
        plusButton.setBounds(109, 173, 43, 23);

        minusButton.setText("-");
        minusButton.setToolTipText("subtract");
        minusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minusButtonActionPerformed(evt);
            }
        });
        getContentPane().add(minusButton);
        minusButton.setBounds(195, 173, 39, 23);

        AnswerLabel.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        AnswerLabel.setText("Atsakymas yra : ");
        AnswerLabel.setToolTipText("");
        getContentPane().add(AnswerLabel);
        AnswerLabel.setBounds(109, 207, 125, 18);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculator.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 400, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secondNumberTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secondNumberTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secondNumberTextActionPerformed

    private void plusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plusButtonActionPerformed
        int sk1, sk2;
        try { 
        sk1 = Integer.parseInt(
                this.FirstNumberText.getText());
    }                                                                                    
       catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Blogas pirmas skaicius",
                   "Klaida", JOptionPane.ERROR_MESSAGE);
           return;
       }
        try { 
        sk2 = Integer.parseInt(
                this.secondNumberText.getText());
    }                                          
       catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Blogas antras skaicius",
                   "Klaida", JOptionPane.ERROR_MESSAGE);
           return;
       }
        int atsakymas = sk1 + sk2;
        this.AnswerLabel.setText(
        "Atsakymas yra :"+ atsakymas);
    }//GEN-LAST:event_plusButtonActionPerformed

    private void minusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minusButtonActionPerformed
        int sk1, sk2;
        try { 
        sk1 = Integer.parseInt(
                this.FirstNumberText.getText());
    }                                                                                    
       catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Blogas pirmas skaicius",
                   "Klaida", JOptionPane.ERROR_MESSAGE);
           return;
       }
        try { 
        sk2 = Integer.parseInt(
                this.secondNumberText.getText());
    }                                          
       catch (Exception e) {
           JOptionPane.showMessageDialog(this, "Blogas antras skaicius",
                   "Klaida", JOptionPane.ERROR_MESSAGE);
           return;
       }
        int atsakymas = sk1 - sk2;
        this.AnswerLabel.setText(
        "Atsakymas yra :"+ atsakymas);
    }//GEN-LAST:event_minusButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SkaiciuoklesForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SkaiciuoklesForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SkaiciuoklesForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SkaiciuoklesForma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SkaiciuoklesForma().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AnswerLabel;
    private javax.swing.JTextField FirstNumberText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton minusButton;
    private javax.swing.JButton plusButton;
    private javax.swing.JTextField secondNumberText;
    // End of variables declaration//GEN-END:variables
}
